### ISSUE TITLE
As an employer, I would like my job posting to appear on the first page for some time so that it does not get rolled down by daily feeds - (Ticket courtesy - Justin Johnson)

### ISSUE THREAD

**Issue by vhazrati** [NashTech-Labs/scalajobz#17]
There should be a way to post sticky job postings. Premium postings.

**Comment by ruchijindal** [comment]
Post your Premium Job on Scalajobz.It is a sticky job for pages 1,2 and 3. There are 2 premium jobs per page(for first three pages only) which would show on the top of the page and stay there for next 10 days.

Maximise the visibility of your job postings and attract more candidates to your jobs.

It would be visible right on the top always for the next 10 days.

Job post receives a distinguished level of exposure on the jobs page by appearing with a  .

Your job will be amongst the top  results in the relevant search filters.

Premium jobs have a place of their own, they do not scroll down like other jobs when new jobs are added.

All the people who have signed for job mailers, get the premium job everyday along with their job search criteria in their email.

Premium Job Posting Packages

Page 1: $298
Page 2: $198
Page 3 : $98

If you have questions or require clarifications then  please feel free to contact us
