### ISSUE TITLE
Publish updates on a Rss feed

### ISSUE THREAD

**Issue by agourlay** [NashTech-Labs/scalajobz#21]
I am not a big twitter user and i find that the quantity of jobs posted daily can be a bit overwhelming sometimes therefore not really readable on a Twitter client.

Is it possible to publish those updates on a RSS feed?
It would be easier to keep track of the new scala jobs I am interested in.

Thanks

Keep up the good work :+1:

**Comment by ruchijindal** [comment]
Hi Agourlay,

Thanks for writing in!

We admire your suggestion of RSS feed and would try to introduce this in future but for now we have the feature of "Daily Job Alerts".  Just subscribe yourself for daily job alerts with Scalajobz for your interested search criteria and then you would get the job alerts mail daily.
