### ISSUE TITLE
Navigation hassles

### ISSUE THREAD

**Issue by deanwampler** [NashTech-Labs/scalajobz#6]
Two problems:
1) In the top-level table view, you can't right-click a position to open it in another window. cmd+click doesn't work either.  You have to click it, look at the listing, then go back.
2) Even worse, when you go back after looking at a listing, it takes you back to the first page of listings, not the page you were on.

**Comment by ruchijindal** [comment]
Hi Dean,

Thanks for writing in! 

Now when we click on a job, its details gets open in a new window. 

For Now I am closing this issue If you want more changes then please let me know.
