### ISSUE TITLE
As a job seeker, I would like ScalaJobz to include a privacy policy so that the community sharing their information is confident that the information would not be misused (ticket credit - Eric Anderson)

### ISSUE THREAD

**Issue by vhazrati** [NashTech-Labs/scalajobz#7]
Include a strict privacy policy so that the collected information is not misused.

**Comment by Nexus6** [comment]
"not be misused" is a bit vague.  I would like to see a privacy policy that states, among other things:

1) How end user data (contact info for recruiters, prospective employees, credentials, CVs, etc) MAY possibly be used by Knoldus or third parties.  Specifically what types of data are being addressed.
2) How end-user data will NOT be shared with, or used by, Knoldus or third parties.  Specifically what types of data are being addressed.
3) What kinds of user tracking is performed by the site as deployed.  I think this would be mostly about cookies set by the site, and those (if any) that are set by third parties.
4) Information about mechanisms of controlling sharing of data, if any.  This could be especially important for job-seekers who might want their information to be visible in only certain ways to certain people.  LinkedIn controls might be one example of how these controls could be implemented.

I'm sure that more will come to mind, but that's a start.

**Comment by vhazrati** [comment]
Excellent points Nexus6. That makes the acceptance criteria better.

**Comment by ruchijindal** [comment]
@Nexus6, Eric could you please review the privacy policy and provide your feedback.

Scalajobz privacy policy : http://www.scalajobz.com/privacyPolicy

For Now I am closing this issue If you want more updates  then please let me know.
