### ISSUE TITLE
Edit Your Profile

### ISSUE THREAD

**Issue by egp** [NashTech-Labs/scalajobz#8]
Edit Your Jobs does something, but Edit Your Profile is apparently a no-op

**Comment by ruchijindal** [comment]
Hi Egp,  

Edit Profile option would work only if You are registered with Scalajobz . If you enrolled or Sign in through any social profile (Google, Face-book, Linked-in , Twitter) then you have no Login Credentials( Email Id & Password) So no need to edit them.

**Comment by egp** [comment]
ok, that makes sense now.
I logged in through Google.

On Monday, December 31, 2012, Ruchi Jindal wrote:

> Hi Egp,
> 
> Edit Profile option would work only if You are registered with Scalajobz .
> If you enrolled or Sign in through any social profile (Google, Face-book,
> Linked-in , Twitter) then you have no Login Credentials( Email Id &
> Password) So no need to edit them.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/knoldus/scalajobz/issues/8#issuecomment-11772824.

## 

"Edward G Prentice" egp@egp.net
